services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build:
      context: ./backend
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/orii
      - ORIGIN=http://localhost:5173
      - JWT_SECRET=devsecret
      - APP_URL=http://localhost:5173
      - ALLOW_DEV_VERIFY=true
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
volumes:
  mongo-data:
